### ISSUE TITLE
GenZbundle时报错

### ISSUE THREAD

**Issue by KitaKita116** [king3soft/ZBundleTable#2]
分部类代码如下：
`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System.Collections.Generic;
using ZBundleTable;

[GenerateWrap("achieve_ui.txt",true)]
public partial class Achieve_ui : IZbundleSerialize
{
    [TableColumnName("TableTitle")] 
    public string tableTitle { get; set; }
    
    [TableColumnName("TableType")] 
    public ulong tableType { get; set; }
    
    [TableColumnName("AchieveType"), List(typeof(int))] 
    public List<int> achieveType { get; set; }

    [TableColumnName("Weight")] 
    public int weight { get; set; }

    [TableColumnName("Atlas")] 
    public string atlas { get; set; }

    [TableColumnName("Icon")] 
    public string icon { get; set; }

    [TableColumnName("Stage")] 
    public int stage { get; set; }
    
    public ulong GetKey()
    {
        return tableType;
    }
}
`
测试代码如下：
`using System.Collections;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

public class TableTest : MonoBehaviour
{
    public void Awake()
    {
        if (!ZbundleTableMgr.inited)
        {
            ZbundleTableMgr.Init(file =>
                {
#if UNITY_EDITOR
                    return "Assets/Setting/CSV/" + file;
#else
                return Application.persistentDataPath + "/" + file;
#endif
                },
                file =>
                {
#if UNITY_EDITOR
                    return "Assets/Setting/Zbundle/" + file;
#else
                return Application.persistentDataPath + "/" + file;
#endif
                },
                file =>
                {
#if UNITY_EDITOR
                    return "Assets/Setting/Dict/" + file;

#else
                    return Application.persistentDataPath + "/" + file;
#endif
                });
        }
#if UNITY_EDITOR
        EditorApplication.playModeStateChanged += OnPlayModeStateChanged;
    }

    private void OnPlayModeStateChanged(PlayModeStateChange state)
    {
        if (state == PlayModeStateChange.ExitingPlayMode)
        {
            Close();
        }
#endif
    }

    public void WrapLoadZBundle()
    {
        ulong[] keys = ZbundleTableMgr.GetAllKey<Achieve_ui>();
        for (int i = 0; i < keys.Length; i++)
        {
            Achieve_ui buff = ZbundleTableMgr.Get<Achieve_ui>(keys[i]);
            Debug.Log($"buff: {buff.tableTitle} {buff.tableType}  {buff.achieveType} {buff.weight} {buff.atlas} {buff.icon} {buff.stage}");
            for (int j = 0; j < buff.achieveType.Count; j++)
            {
                Debug.Log(buff.achieveType[j]);
            }
        }
    }

    public void Close()
    {
        ZbundleTableMgr.CloseAllTable();
    }
}
`

**Comment by luyufeng1999** [comment]
已定位问题, ZBuffer回收时未清空
